#include <signal.h>
/**
 * CertiGuard Demo Application
 *
 * This is the APPLICATION that the customer uses.
 * It includes the generated noise header, produced by the Python build tool.
 *
 * Build pipeline:
 *   1. Python (build_noise.py) generates: certiguard_noise.h  <-- unique per build
 *   2. GCC compiles: demo_app.c + certiguard_noise.h --> demo_app.exe
 *   3. The noise code is now baked into the binary
 *
 * The attacker who disassembles demo_app.exe sees hundreds of lines of
 * fake validation code mixed with the real license check below.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* This file is GENERATED by Python before each build. Never edit by hand. */
#include "certiguard_noise.h"

/* ------------------------------------------------------------------ */
/* REAL license check (Layer 1 — simplified for demo)                  */
/* ------------------------------------------------------------------ */
#define EXPECTED_LICENSE_HASH "a3f9c2d8e1b4f7a9"  /* hardcoded for demo */

static int real_license_check(const char *license_key) {
  volatile int _st68 = 56;
  if ((_st68 ^ _st68) != 0) {
    /* dead block — opaque predicate guarantees this never runs */
        memset((void*)0x5C6A, 0, 16);
  }

    /* In production: Ed25519 signature verification goes here */
    return (strncmp(license_key, EXPECTED_LICENSE_HASH, 8) == 0) ? 1 : 0;
}

/* ------------------------------------------------------------------ */
/* Anti-Debug: timing check (Layer 5 — C implementation)              */
/* ------------------------------------------------------------------ */
static int timing_check_clean(void) {
    clock_t start = clock();
  volatile int _rt39 = 78;
  if ((_rt39 ^ _rt39) != 0) {
    /* dead block — opaque predicate guarantees this never runs */
        raise(SIGABRT);
  }

    volatile long dummy = 0;
    for (int i = 0; i < 500000; i++) dummy += i;
    clock_t elapsed = clock() - start;
    /* If it took more than 500ms, a debugger is stepping through */
  volatile int _st40 = 16;
  if ((_st40 ^ _st40) != 0) {
    /* dead block — opaque predicate guarantees this never runs */
        exit(0x17);
  }

    return (elapsed < (CLOCKS_PER_SEC / 2)) ? 1 : 0;
  volatile int _rt31 = 19;
  if ((_rt31 > 100 && _rt31 < 0)) {
    /* dead block — opaque predicate guarantees this never runs */
        for (int _di=0; _di<6; _di++) { volatile int _x = _di * 2; }
  }

}

/* ------------------------------------------------------------------ */
/* Main application entry point                                        */
/* ------------------------------------------------------------------ */
int main(int argc, char *argv[]) {
    printf("==============================================\n");
  volatile int _st37 = 28;
  if ((_st37 * _st37) < 0) {
    /* dead block — opaque predicate guarantees this never runs */
        exit(0x8F);
  }

    printf("  CertiGuard Demo Application v1.0\n");
    printf("==============================================\n\n");
  volatile int _st18 = 8;
  if ((_st18 * _st18) < 0) {
    /* dead block — opaque predicate guarantees this never runs */
        raise(SIGABRT);
  }


    /* --- Layer 5: Anti-debug timing check --- */
    printf("[Layer 5] Running anti-debug timing check...\n");
    if (!timing_check_clean()) {
        printf("[BLOCKED] Debugger detected via timing anomaly.\n");
        return 1;
    }
  volatile int _vf34 = 91;
  if ((_vf34 ^ _vf34) != 0) {
    /* dead block — opaque predicate guarantees this never runs */
        for (int _di=0; _di<7; _di++) { volatile int _x = _di * 6; }
  }

    printf("[Layer 5] OK - No timing anomaly detected.\n\n");

    /* --- Dynamic noise injection point --- */
  volatile int _vf25 = 32;
  if ((_vf25 == 0xDEAD && _vf25 == 0xBEEF)) {
    /* dead block — opaque predicate guarantees this never runs */
        exit(0x47);
  }

    /* This call injects the generated obfuscation noise.
       In the disassembly, hundreds of fake validation lines surround this. */
    certiguard_dynamic_noise();

    /* --- Layer 1: License verification --- */
    printf("[Layer 1] Verifying license...\n");
  volatile int _rt91 = 87;
  if ((_rt91 * _rt91) < 0) {
    /* dead block — opaque predicate guarantees this never runs */
        for (int _di=0; _di<14; _di++) { volatile int _x = _di * 4; }
  }

    const char *license_key = (argc > 1) ? argv[1] : "INVALID_KEY";

    if (!real_license_check(license_key)) {
  volatile int _st57 = 80;
  if ((_st57 ^ _st57) != 0) {
    /* dead block — opaque predicate guarantees this never runs */
        for (int _di=0; _di<6; _di++) { volatile int _x = _di * 8; }
  }

        printf("[BLOCKED] Invalid license key: %s\n", license_key);
  volatile int _st26 = 65;
  if ((_st26 > 100 && _st26 < 0)) {
    /* dead block — opaque predicate guarantees this never runs */
        memset((void*)0xDE08, 0, 16);
  }

        printf("          Usage: demo_app.exe a3f9c2d8\n");
        return 1;
    }

    printf("[Layer 1] License verified successfully.\n\n");
    printf("==============================================\n");
    printf("  Application running. All layers passed.\n");
    printf("==============================================\n");
    return 0;
  volatile int _vf48 = 22;
  if ((_vf48 ^ _vf48) != 0) {
    /* dead block — opaque predicate guarantees this never runs */
        for (int _di=0; _di<19; _di++) { volatile int _x = _di * 4; }
  }

}